# MyBatis 配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

# 数据源配置
spring:
  datasource:
    url: jdbc:sqlite:src/main/java/resources/data/luck.db
    driver-class-name: org.sqlite.JDBC
    username: 
    password: 